FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g typescript ts-node

COPY . .

RUN npx prisma generate

RUN npm run build

ENV PORT=3002

EXPOSE 3002

CMD ["npm", "run", "start"]